[package]
name = "lyagushka"
version = "0.1.0"
edition = "2021"

[lib]
name = "lyagushka"
crate-type = ["cdylib"]

[dependencies]
atty = "0.2.14"
pyo3 = "0.20.2"
rand = "0.8.5"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
