[package]
name = "lyagushka"
version = "1.1.0"
edition = "2021"
crate-type = ["cdylib"]

[dependencies]
atty = "0.2.14"
pyo3 = { version = "0.20.2", features = ["extension-module"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"